workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up debug keystore
        script: |
          echo "Creating debug keystore..."
          keytool -genkey -v -keystore android/app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      - name: Get Flutter dependencies
        script: flutter packages pub get
      - name: Build Android APK
        script: flutter build apk --debug --verbose
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - riadov001@gmail.com

  ios-build:
    name: iOS Build  
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.myjantes.manager
      groups:
        - app_store_connect
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: flutter packages pub get
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Build iOS without signing
        script: flutter build ios --no-codesign --verbose
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - riadov001@gmail.com