name: myjantes_manager
description: Application Flutter pour la réservation et gestion de services de rénovation de jantes automobiles

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Navigation
  go_router: ^12.1.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # Date & Time
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
